---
displayName: Python-custom
description: Python Stack with Python 3.8
tags: ["Community", "Centos", "Python", "pip"]
icon: /images/python.svg
links:
  v2: https://github.com/debkantap/python-hello-world-cus-devfile/tree/main
